version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - dbdata:/var/opt/mssql
  
  identity-server:
    build:
      context: ../../
      dockerfile: templates/service/host/IdentityServerHost/Dockerfile
    depends_on:
      - sqlserver      
  
  file-management:
    build:
      context: ../../
      dockerfile: templates/service/host/Xhznl.FileManagement.Host/Dockerfile
    depends_on:
      - sqlserver
      - identity-server

volumes:
  dbdata: